### ISSUE TITLE
Why no finalizer in for public sealed class OcvOp : IDisposable

### ISSUE THREAD

**Issue by Noemata** [shimat/opencvsharp_samples#8]
I'm curious why no finalizer is needed for the OcvOp class in the CameraOpenCV sample.

I liked the use of the C# 8.0 using syntax.  That's a nice simplification.  I would have thought a finalizer would have been required for the BackgroundSubtractorMOG2 object.  Is it not needed because it uses a safe handle under the hood, or is there some other reason?

I was looking at these docs:

https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by shimat** [comment]
On the MSDN page, destructors are written for classes that have only managed resources. We should write destructor when the class has some native resources. BackgroundSubtractorMOG2 is  managed instance.

And since the instance of the OcvOp class is retained until the end of the program, it does not have to write Dispose and ~Destructor. The destructor is called just before the program ends. So I think it is not necessary to write it. (I wrote Dispose just in case but it is also not necessary in this sample.)
Since it is a sample program, I think strict release processing could be omitted.

**Comment by Noemata** [comment]
Thank you for the clarification.  I have done most of the needed cleanup on the sample.  Up to you, if you add me to the contributors on your sample repo, I can take care of folding the changes in.  All that's left is param handling and coming up with a managed version of the Histogram routine.  I don't think I'm the best candidate to do an optimal managed version of the Histogram code.  The cleaned up code is up on: https://github.com/Noemata/OCVSharpTest

I'll have the param handling in soon.  Need to come up with a slightly better way of handling min/max slider values.

I'm going to remove the refs to my version of OpenCvSharp shortly.  Thank you very much for getting this done!

**Comment by Noemata** [comment]
Just noticed your remark about forking.  I'll go the fork route for the changes.

**Comment by shimat** [comment]
Sorry for my poor English. I corrected my strange explanation above.
I close this issue and wait for your commit. Thank you!
